version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'zealthy_help_desk'
      MYSQL_USER: 'zealthy'
      MYSQL_PASSWORD: 'password123'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=zealthy
      - DB_PASS=password123
      - DB_NAME=zealthy_help_desk
    restart: unless-stopped
    command: >
      /bin/bash -c "
        while !</dev/tcp/mysql/3306; do
          echo 'Waiting for MySQL...'
          sleep 1
        done
        npm run db:seed && npm run server:start
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    links:
      - api
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: api

  nginx-proxy:
    depends_on:
      - api
      - frontend
    image: nginx:alpine
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

volumes:
  mysql_data: